# Generated by Django 6.0.6 on 2026-06-06 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.AddField(
            model_name='meal',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='breakfast',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='lunch',
            field=models.BooleanField(default=True),
        ),
    ]
