# Generated by Django 6.0.6 on 2026-06-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_meal_user_meal_member_alter_meal_breakfast_and_more'),
        ('members', '0002_alter_member_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('member', 'date')},
        ),
    ]
