# Generated by Django 6.0.6 on 2026-06-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meal_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='meal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='lunch',
        ),
    ]
