# Generated by Django 6.0.6 on 2026-06-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_alter_meal_unique_together_remove_meal_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='breakfast',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=4),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dinner',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
        ),
    ]
