# Generated by Django 6.0.6 on 2026-06-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0005_alter_meal_breakfast_alter_meal_dinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='breakfast',
            field=models.DecimalField(choices=[(0, '0'), (0.5, '0.5'), (1, '1'), (1.5, '1.5'), (2, '2'), (2.5, '2.5'), (3, '3')], decimal_places=1, default=0.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='meal',
            name='dinner',
            field=models.DecimalField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], decimal_places=1, default=1, max_digits=3),
        ),
    ]
