# Generated by Django 6.0.6 on 2026-06-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
